services:
  - type: web
    name: team-task-manager
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:create_app()
    envVars:
      - key: FLASK_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
